### ISSUE TITLE
No heading to know what it is about in home page  

### ISSUE THREAD

**Issue by Jpulisic27** [giftthedeveloper/backend-zenith-moment-2.0#36]
I will like to recommend heading in home page to know what it is about

**Comment by giftthedeveloper** [comment]
Hi. This is an api not a website. Apis dont have headings neither do they have home page. I suggest you read more about how to test or review an api.

**Comment by Jpulisic27** [comment]
Alright Thank you for your response though I think api usually have title to provide additional information for the content
